var potions=[[1,"Potion of Animal Control"],[4,"Potion of Clairaudience"],[7,"Potion of Clairvoyance"],[10,"Potion of Climbing"],[13,function(){return "Potion of Delusion ("+pickRandom(potions)+")"}],[18,"Potion of Diminution"],[21,"Potion of Dragon Control"],[24,"Potion of ESP"],[27,"Potion of Extra-Healing"],[29,"Potion of Fire Resistance"],[32,"Potion of Flying"],[37,"Potion of Gaseous Form"],[41,function(){return "Potion of "+pickRandom([[1,'Cloud'],[3,'Fire'],[7,'Frost'],[11,'Hill'],[16,'Stone'],[20,'Storm']])+" Giant Control"}],[44,"Potion of Giant Strength"],[48,"Potion of Growth"],[51,"Potion of Healing"],[55,"Potion of Heroism"],[59,"Potion of Human Control"],[62,"Potion of Invisibility"],[65,"Potion of Invulnerability"],[67,"Potion of Levitation"],[70,"Potion of Longevity"],[72,"Oil of Sharpness"],[74,"Oil of Slipperiness"],[76,"Philter of Love"],[79,"Potion of Plant Control"],[82,"Poison"],[84,"Potion of Polymorph"],[86,"Potion of Speed"],[89,"Potion of Super-Heroism"],[91,"Potion of Sweet Water"],[94,"Potion of Treasure Finding"],[96,"Potion of Undead Control"],[98,"Potion of Water Breathing"]];

var rings=[[1,"Ring of Command Animal"],[5,"Ring of Command Human"],[10,"Ring of Command Plant"],[16,function(){return "Ring of Delusion ("+pickRandom(rings)+")"}],[26,"Ring of Djinni Calling"],[28,"Ring of Fire Resistance"],[39,"Ring of Invisibility"],[50,function(){return "Ring of Protection ("+pickRandom([[1,"+1"],[81,"+2"],[92,"+2, 5' radius"],[93,"+3"],[100,"+3, 5' radius"]])+")"}],[71,"Ring of Regeneration"],[73,function(){var r=d(1,6),spells="";for(var i=0;i<r;i++) spells+=", "+pickRandom((rand(0,1)?arcaneList[rand(0,5)]:divineList[rand(0,4)]));return "Ring of Spell Storing ("+spells.substring(2)+")"}],[75,function(){return "Ring of Spell Turning ("+d(2,6)+")"}],[80,"Ring of Telekinesis"],[82,"Ring of Water Walking"],[88,"Ring of Weakness"],[95,function(){return "Ring of Wishes ("+d(1,4)+")"}],[98,"Ring of X-Ray Vision"]];


var scrolls=[[1,function(){return "Cursed Scroll: "+pickRandom(["The victim loses a random magic item.","One random ability score suffers a -4 penalty.","The victim may not gain new experience.","The victim's level is reduced by 1.","The victim is polymorphed, as polymorph other, into a small animal.","The victim is rendered blind."]);}],[6,"Ward against Elementals"],[16,"Ward against Lycanthropes"],[26,"Ward against Magic"],[31,"Ward against Undead"],[41,function(){return createScroll(1);}],[56,function(){return createScroll(2);}],[67,function(){return createScroll(3);}],[70,function(){return createScroll(4);}],[73,function(){return createScroll(5);}],[75,function(){return createScroll(6);}],[76,function(){return createScroll(7);}],[77,function(){return "Treasure Map (to "+addCommas(d(1,4)*1000)+"gp)";}],[81,function(){return "Treasure Map (to "+addCommas(d(5,6)*1000)+"gp)";}],[86,function(){return "Treasure Map (to "+addCommas(d(6,6)*1000)+"gp)";}],[88,function(){return "Treasure Map (to "+addCommas(d(5,6)*1000)+"gp, "+pickGem(5,6,1,gemList)+")";}],[90,function(){return "Treasure Map (to "+pickGem(1,6,1,gemList)+", "+pickGem(2,10,1,jewelryList)+")";}],[92,function(){return "Treasure Map (to "+pickAny(1)+")";}],[94,function(){return "Treasure Map (to "+pickAny(2)+")";}],[96,function(){return "Treasure Map (to "+pickRandom(pickRandom([[01,potions],[21,rings],[26,scrolls],[57,wands],[62,misc]],66)),+', '+pickRandom(pickRandom([[01,potions],[21,rings],[26,scrolls],[57,wands],[62,misc]],66))+', '+pickRandom(pickRandom([[01,potions],[21,rings],[26,scrolls],[57,wands],[62,misc]],66))+")";}],[97,function(){return "Treasure Map (to "+pickAny(3)+", "+pickRandom(potions)+")";}],[98,function(){return "Treasure Map (to "+pickAny(3)+", "+pickRandom(potions)+", "+pickRandom(scrolls)+")";}],[99,function(){return "Treasure Map (to "+addCommas(d(5,6)*1000)+"gp, "+pickAny(1)+")";}],[100,function(){return "Treasure Map (to "+pickGem(1,6,1,gemList)+", "+pickAny(2)+")";}]];
var languagesMine=[[1,"Nobiran"],[10,"Old Elven"],[15,"Common"],[25,"Draconic"],[45,"Zaharan"],[55,"Dwarven"],[60,"Gnomish"],[65,"Mejastan"],[75,"Elven"],[80,"Fae"],[90,"Ancient Zaharan"],[100,"Thrassian"],[110,"Kobold"],[115,"Hobgoblin"],[120,"Orc"],[130,"Gnoll"],[140,"Goblin"],[150,"Troll"],[160,"Mer"],[165,"Extraplanar"],[170,"Planar (Air)"],[175,"Planar (Water)"],[180,"Planar (Fire)"],[185,"Planar (Earth)"],[190,"Thieves' Cant (Mareten)"],[194,"Thieves' Cant (Wild Plains)"],[198,"Thieves' Cant (Zahar)"]];
var languagesDefault=[[1,"Classical Auran"],[21,"Common"],[31,"Draconic"],[51,"Dwarven"],[71,"Elven"],[91,"Ancient Zaharan"],[100,"Thrassian"],[110,"Kobold"],[115,"Hobgoblin"],[120,"Orc"],[130,"Gnoll"],[140,"Goblin"],[150,"Troll"],[160,"Mer"],[165,"Extraplanar"],[170,"Gnomish"],[180,"Kemeshi"],[190,"Thieves' Cant"]];
var languages=languagesMine;
var scrollTypeMine=[[1,"Arcane"],[3,"Library"],[4,"Divine"]];
var scrollTypeDefault=[[1,"Arcane"],[4,"Divine"]];
var scrollType=scrollTypeMine;
var arcaneScrollSpellLevel=[[01,1],[26,2],[51,3],[71,4],[86,5],[96,6],[98,7],[99,8],[100,9]];
var divineScrollSpellLevel=[[01,1],[26,2],[51,3],[71,4],[86,5],[96,6],[99,7]];
var arcaneList=[["Burning Hands","Charm Person","Chameleon","Choking Grip","Detect Magic","Floating Disc","Hold Portal","Jump","Light","Light reversed","Magic Missile","Magic Mouth","Magic Rope","Protection from Evil","Protection from Evil reversed","Read Languages","Sharpness","Shield","Silent Step","Sleep","Slipperiness","Spider Climb","Summon Berserkers","Unseen Servant","Ventriloquism","Wall of Smoke"],["Alter Self","Continual Light","Continual Light reversed","Deathless Minion","Detect Evil","Detect Evil reversed","Detect Invisible","Detect Secret Doors","ESP","Glitterdust","Gust of Wind","Hypnotic Pattern","Inaudibility","Invisibility","Knock","Levitate","Locate Object","Mirror Image","Necromantic Potence","Ogre Power","Phantasmal Force","Stinking Cloud","Summon Hero","Uncanny Gyration","Web","Wizard Lock"],["Clairvoyance","Clairaudience","Chimerical Force","Command Person","Dismember","Dispel Magic","Earth’s Teeth","Enervate","Fireball","Fly","Gaseous Form","Growth","Growth reversed","Haste","Haste reversed","Hold Person","Infravision","Invisibility 10' radius","Lightning Bolt","Nondetection","Protection from Evil, Sustained","Protection from Evil, Sustained reversed","Protection from Normal Missiles","Skinchange","Summon Winged Steed","Telepathy","Water Breathing"],["Charm Monster","Command Plant","Confusion","Conjure Ooze","Dimension Door","Fear","Find Treasure","Giant Strength","Growth of Plants","Growth of Plants reversed","Hallucinatory Terrain","Magic Carpet","Massmorph","Minor Globe of Invulnerability","Polymorph Other","Polymorph Self","Remove Curse","Remove Curse reversed","Scry","Spectral Force","Spell Storing","Summon Fantastic Creature","Wall of Fire","Wall of Ice","Wall of Wood","Wizard Eye"],["Animate Dead","Adaptation","Cloudkill","Cone of Cold","Cone of Paralysis","Conjure Elemental","Contact Other Plane","Control Undead","Curse of Swine","Enchanted Container","Feeblemind","Hold Monster","Magic Jar","Mass Infravision","Panic","Passwall","Phantasmal Killer","Protection from Normal Weapons","Scouring Wind","Telekinesis","Teleport","Transform Rock to Mud","Transform Rock to Mud reversed","Wall of Stone","X-Ray Vision"],["Anti-Magic Shell","Control Plants","Control Weather","Death Spell","Detect Ritual Magic","Disintegrate","Enslave","Flesh to Stone","Flesh to Stone reversed","Geas","Geas reversed","Globe of Invulnerability","Invisible Stalker","Lower Water","Move Earth","Oblivion","Permanent Illusion","Programmed Illusion","Projected Image","Reincarnate","Summon Djinni","Torpor","Trollblood","Wall of Corpses","Wall of Force","Wall of Iron"],["Cancellation","Energy Drain","Phase Door","Spell Turning"],["Opposition","Permanency","Summon Efreeti","Temporal Stasis"],["Life Trapping","Plague","Undead Legion","Wish"]];
var divineList=[["Angelic Choir","Cause Fear","Command Word","Cure Light Wounds","Cure Light Wounds reversed","Darkness","Delay Disease","Detect Danger","Detect Evil","Detect Good","Detect Magic","Faerie Fire","Fellowship","Light","Locate Animal or Plant","Pass Without Trace","Predict Weather","Protection from Evil","Protection from Good","Purify Food and Water","Purify Food and Water reversed","Read Languages","Remove Fear","Remove Fear reversed","Resist Cold","Salving Rest","Sanctuary","Trance","Detect Poison","Detect Undead"],["Augury","Bane","Bless","Chameleon","Charm Animal","Choking Grip","Cure Moderate Wounds","Cure Moderate Wounds reversed","Delay Poison","Detect Charm","Divine Grace","Enthrall","Find Traps","Hold Person","Holy Chant","Locate Object","Magic Mouth","Obscuring Cloud","Produce Fire","Resist Fire","Righteous Wrath","Shimmer","Silence 15' radius","Sleep","Snake Charm","Speak with Animals","Spiritual Weapon","Swift Sword","Unseen Servant","Ventriloquism","Warp Wood"],["Alter Self","Call Lightning","Charm Person","Continual Darkness","Continual Light","Cure Blindness","Cure Blindness reversed","Cure Disease","Cure Disease reversed","Cure Major Wounds","Cure Major Wounds reversed","Curse","Detect Curse","Detect Curse reversed","Detect Invisible","ESP","Eyes of the Eagle","Feign Death","Glyph of Warding","Growth of Animals","Glitterdust","Invisibility","Invulnerability to Evil","Levitate","Locate Object","Mirror Image","Necromantic Potence","Phantasmal Force","Prayer","Prot. from Normal Missiles","Remove Curse","Speak with Dead","Sphere of Visibility","Striking","Water Breathing","Water Walking","Winged Flight"],["Animate Dead","Cause Serious Wounds","Chimerical Force","Clairaudience","Clairvoyance","Command Animals","Control Undead nec","Create Water","Cure Serious Wounds","Death Ward","Dispel Magic","Divination","Fate","Fly","Infravision","Neutralize Poison","Neutralize Poison reversed","Nondetection","Protection from Evil, Sustained","Protection from Good, Sustained","Skinchange","Smite Undead","Smite Undead reversed","Speak with Plants","Spirit of Healing","Spirit of Healing reversed","Sticks to Snakes","Summon Animals","Telepathy","Tongues","Tongues reversed","Vigor","Water Breathing"],["Atonement","Call Dragon","Charm Monster","Command Person","Commune","Control Animals","Control Winds","Create Food","Cure Critical Wounds","Dispel Evil","Fear","Finger of Death","Flame Strike","Growth of Plants","Insect Plague","Lower Water","Magic Carpet","Polymorph Other","Polymorph Self","Protection from Normal Weapons","Quest","Quest reversed","Reincarnation","Restore Life and Limb","Restore Life and Limb reversed","Scry","Spectral Force","Strength of Mind","Strength of Mind reversed","Summon Weather","Sword of Fire","True Seeing"],["Forbiddance","Harvest","Longevity","Longevity reversed","Regeneration","Regeneration reversed"],["Cataclysm","Energy Drain","Miracle","Resurrection"]];
var libraryList=[["Bedtime Story","Command Word","Wooden Object","Darkness","Doorfinder","Fellowship","Lifted","Light","Magic Mouth","Magic Rope","Magical Shield","Mountain","Protection from Evil","Puff of Air","Read Languages","Teleport Object","Trapfinder","Ventriloquism","Weaken","Yard Light"],["Continual Darkness","Continual Light","Copy","Find","Firewall","Inaudibility","Insulation","Invisibility","Lead Feet","Magical Armor","Mass Confusion","Mirror Image","Pepperbox","Phantasmal Force","Plant-to-Stone","Speed Force","Statues","Teleport Person","Traveler","Weakness"],["Absolutely Charming","Alter Self","Chimerical Force","Clairaudience","Clairvoyance","Eyes of the Eagle","Fine Finder","Glyph of Warding","Immortal Warrior","Invisibility 10' radius","Nondetection","Protection from Evil, Sustained","Protection from Normal Missiles","Remove Curse","Roc On","Stone-to-flesh","Stop","Summon Weapons","Teleportitus","Water Breathing"],["Charm Monster","Command Plant","Cone of Command","Create Armor","Death Ward","Fear","Find Ritual","Flesh-to-Stone","Hallucinatory Terrain","Home","Impart","Massmorph","Mindsting","Return","Scripted","Speak with Plants","Spectral Force","Sphere of Atmos","Sticks to Snakes","Tongues"],["Avoidance","Blast","Corporialize","Disintegrating Illusion","Enchanted Container","End Quest","Grasping Hands","Gusting Shock","Immortal Guardian","Immunity","Invincibility","Magic Jar","Mass Climb","Mire","Phantasmal Killer","Planeshift","Quest","Stone-to-Creature","True Seeing","X-Ray Vision"],["Anti-Magic Shell","Carpet Jet","Clone","Create Maze","Electrify","Eviction","Forbiddance","Jail","Let's Read!","Magic Immunity","Permanent Illusion","Programmed Illusion","Projected Image"],["Cancellation","Energy Drain","Phase Door","Spell Turning"],["Opposition","Permanency","Temporal Stasis"],["Life Trapping","Plague","Wish"]];

function createScroll(n){
 var spelltype=pickRandom(scrollType);
 var spells="";
 for(var i=0;i<n;i++){
  var lvl;
  if(spelltype=="Divine")
   lvl=pickRandom(divineScrollSpellLevel);
  else
   lvl=pickRandom(arcaneScrollSpellLevel);
  if(spelltype=="Arcane")
   spells+="; lvl "+lvl+" "+pickRandom(arcaneList[lvl-1]);
  else if(spelltype=="Divine")
   spells+="; lvl "+lvl+" "+pickRandom(divineList[lvl-1]);
  else if(spelltype=="Library")
   spells+="; lvl "+lvl+" "+pickRandom(libraryList[lvl-1]);
 }
 return pickRandom(languages)+' '+spelltype+' scroll with '+n+' spell(s) ('+spells.substring(2)+')';
}

var wands=[[1,function(){return "Rod of Cancellation (1 charge)"}],[7,function(){return "Rod of Resurrection ("+d(2,6)+" charges)"}],[9,function(){return "Staff of Commanding [D] ("+d(3,10)+" charges)"}],[11,"Staff of Healing [D]"],[21,function(){return "Staff of Power [A] ("+d(3,10)+" charges)"}],[23,function(){return "Staff of Striking [D] ("+d(3,10)+" charges)"}],[27,function(){return "Staff of Withering [D] ("+d(3,10)+" charges)"}],[29,function(){return "Staff of Wizardry [A] ("+d(3,10)+" charges)"}],[30,"Staff of the Serpent [D]"],[37,function(){return "Wand of Cold ("+d(2,10)+" charges)"}],[41,function(){return "Wand of Detecting Enemies ("+d(2,10)+" charges)"}],[46,function(){return "Wand of Detecting Magic ("+d(2,10)+" charges)"}],[51,function(){return "Wand of Detecting Metals ("+d(2,10)+" charges)"}],[56,function(){return "Wand of Detecting Secret Doors ("+d(2,10)+" charges)"}],[61,function(){return "Wand of Detecting Traps ("+d(2,10)+" charges)"}],[65,function(){return "Wand of Device Negation ("+d(2,10)+" charges)"}],[70,function(){return "Wand of Fear ("+d(2,10)+" charges)"}],[75,function(){return "Wand of Fire Balls ("+d(2,10)+" charges)"}],[80,function(){return "Wand of Illusion ("+d(2,10)+" charges)"}],[85,function(){return "Wand of Lightning Bolts ("+d(2,10)+" charges)"}],[89,function(){return "Wand of Magic Missiles ("+d(2,10)+" charges)"}],[94,function(){return "Wand of Paralyzation ("+d(2,10)+" charges)"}],[97,function(){return "Wand of Polymorphing ("+d(2,10)+" charges)"}]];
var misc=[[1,function(){return "Amulet versus Crystal Balls and ESP";}],[3,function(){return "Apparatus of the Crab";}],[4,function(){return "Bag of Devouring";}],[6,function(){return "Bag of Holding";}],[11,function(){return "Boat, Folding";}],[12,function(){return "Boots of Levitation";}],[15,function(){return "Boots of Speed";}],[18,function(){return "Boots of Traveling and Springing";}],[21,function(){return "Bowl of Commanding Water Elementals";}],[22,function(){return "Bracers of Armor (+"+pickRandom([[01,1],[07,2],[17,3],[37,4],[52,5],[72,6],[87,7]])+")";}],[24,function(){return "Brazier of Commanding Fire Elementals";}],[25,function(){return "Brooch of Shielding";}],[27,function(){return "Broom of Flying";}],[30,function(){return "Censer of Controlling Air Elementals";}],[31,function(){return "Chime of Opening";}],[32,function(){return "Cloak of Protection ("+pickRandom([[1,"+1"],[81,"+2"],[92,"+3"]])+")";}],[34,function(){return "Crystal Ball";}],[37,function(){return "Crystal Ball with Clairaudience";}],[39,function(){return "Crystal Ball with ESP";}],[40,function(){return "Cube of Force";}],[41,function(){return "Cube of Frost Resistance";}],[42,function(){return "Decanter of Endless Water";}],[44,function(){return "Displacer Cloak";}],[46,function(){return "Drums of Panic";}],[47,function(){return "Dust of Appearance";}],[50,function(){return "Dust of Disappearance";}],[53,function(){return "Efreeti Bottle";}],[54,function(){return "Elven Cloak";}],[58,function(){return "Elven Boots";}],[62,function(){return "Eyes of Charming";}],[63,function(){return "Eyes of the Eagle";}],[65,function(){return "Eyes of Petrification";}],[68,function(){return "Flying Carpet";}],[72,function(){return "Gauntlets of Ogre Power";}],[75,function(){return "Girdle of Giant Strength";}],[78,function(){return "Helm of Alignment Changing";}],[81,function(){return "Helm of Comprehending Languages";}],[85,function(){return "Helm of Telepathy";}],[86,function(){return "Helm of Teleportation";}],[87,function(){return "Horn of Blasting";}],[88,function(){return "Medallion of ESP";}],[91,function(){return "Medallion of ESP (90')";}],[93,function(){return "Mirror of Life Trapping";}],[94,function(){return "Mirror of Opposition";}],[95,function(){return "Necklace of Adaptation";}],[96,function(){return "Rope of Climbing";}],[98,function(){return "Scarab of Protection";}],[100,function(){return "Stone of Controlling Earth Elementals";}]];
var swords=[[1,"Sword +1"],[40,"Sword +1 / +2 versus lycanthropes"],[45,"Sword +1 / +2 versus spell casters"],[50,"Sword +1 / +3 versus undead"],[54,"Sword +1 / +3 versus dragons"],[58,"Sword +1 / +3 versus regenerating monsters"],[63,"Sword +1 / +3 versus summoned creatures"],[68,"Sword +1 / light 30' radius"],[76,"Sword +1 / Flame Tongue"],[81,function(){return "Sword +1 / Life Drinker ("+(d(1,4)+4)+" charges)"}],[82,"Sword +1 / locate objects"],[85,function(){return "Sword +1 / Luck Blade ("+(d(1,4)+1)+" wishes)"}],[86,"Sword +2"],[90,"Sword +2 / charm person"],[92,"Sword +3"],[95,"Sword +3 / Frost Brand"],[96,"Sword +3 / Vorpal"],[97,"Sword -1 (cursed)"],[99,"Sword -2 (cursed)"]];
var weapons=[[1,function(){return "Arrows +1 (quantity "+d(2,6)+")"}],[11,function(){return "Arrows +1 (quantity "+d(3,10)+")"}],[13,function(){return "Arrows +2 (quantity "+d(1,6)+")"}],[19,function(){return "Arrows +3 (quantity "+d(1,4)+")"}],[22,function(){return "Arrow +3 / Slaying Arrow ("+pickRandom(["Avians*","Beastmen","Clerics","Dragons","Dwarves","Elementals","Elves","Fighters","Giants","Giant animals","Golems","Mages","Mammals*","Plant-like monsters","Regenerating monsters","Reptiles*","Sea creatures*","Thieves","Undead","Vermin*"])+")"}],[23,"Axe +1"],[32,"Axe +2"],[35,"Bow +1"],[42,function(){return "Crossbow Bolts +1 (quantity "+d(2,6)+")"}],[52,function(){return "Crossbow Bolts +1 (quantity "+d(3,10)+")"}],[54,function(){return "Crossbow Bolts +2 (quantity "+d(1,6)+")"}],[61,function(){return "Crossbow Bolts +3 (quantity "+d(1,4)+")"}],[64,"Dagger +1"],[69,"Dagger +2 / +3 versus beastmen"],[70,"Sling +1"],[76,"Spear +1"],[83,"Spear +2"],[87,"Spear +3"],[88,"War Hammer +1"],[95,"War Hammer +2"],[100,"War Hammer +2 / Dwarven Thrower"]];
var armor=[[01,"Armor +1"],[16,"Armor +1 and Shield +1"],[26,"Armor +1 and Shield +2"],[28,"Armor +1 and Shield +3"],[29,"Armor +2"],[33,"Armor +2 and Shield +1"],[36,"Armor +2 and Shield +2"],[39,"Armor +2 and Shield +3"],[40,"Armor +3"],[41,"Armor +3 and Shield +1"],[42,"Armor +3 and Shield +2"],[43,"Armor +3 and Shield +3"],[44,"Shield +1"],[64,"Shield +2"],[74,"Shield +3"],[80,"Armor -1 (cursed)"],[83,"Armor -2 (cursed)"],[86,"Armor -1 (cursed) and Shield +1"],[87,"Armor -2 (cursed) and Shield +1"],[88,"Armor AC 0 (cursed)"],[91,"Shield -1 (cursed)"],[95,"Shield -2 (cursed)"],[98,"Shield AC 0 (cursed)"]];

var any = [[01,potions],[21,rings],[26,scrolls],[57,wands],[62,misc],[67,swords],[88,weapons],[93,armor]];


function pickAny(x){
 if(!x)
  x=1;
 var str="";
 for(var i=0;i<x;i++)
  str+=", "+pickRandom(pickRandom(any));
 return str.substring(2);
}
